<?php

namespace AppBundle\Repository;

/**
 * AddressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressesRepository extends \Doctrine\ORM\EntityRepository
{
}
