<?php

namespace AppBundle\Repository;

/**
 * CustomersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomersRepository extends \Doctrine\ORM\EntityRepository
{
}
