<?php

namespace AppBundle\Repository;

/**
 * Orders_ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Orders_ProductsRepository extends \Doctrine\ORM\EntityRepository
{
}
