<?php

namespace AppBundle\Repository;

/**
 * PaymentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentsRepository extends \Doctrine\ORM\EntityRepository
{
}
