<?php

namespace AppBundle\Repository;

/**
 * productRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class productRepository extends \Doctrine\ORM\EntityRepository
{
}
